version: '3.1'

services:

  docker-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: nomina
      POSTGRES_USER: nomina
      POSTGRES_PASSWORD: 123456

  docker-nomina:
    # image: nomina:0.0.1
    build: .
    ports:
     - "8080:8080"
    depends_on:
     - docker-postgres

